# Generated by Django 3.0.8 on 2020-07-18 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='name',
        ),
        migrations.AddField(
            model_name='pizza',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='shopapp.PizzaType'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
